
uint32 time
#
float32 robot_pos_x
float32 robot_pos_y
float32 robot_pos_theta
#
float32 setpoint_pos_x
float32 setpoint_pos_y
float32 setpoint_pos_theta
#
float32 goal_point_pos_x
float32 goal_point_pos_y 
#
float32 goal_point_speed_x
float32 goal_point_speed_y
#
float32 asserv_error_x
float32 asserv_error_y
#
float32 command_v
float32 command_omega
#
float32 commande_motor_r
float32 commande_motor_l
#
uint32 manager_state
uint32 controller_state
