#ifndef DEFINES_HPP
#define DEFINES_HPP

/* POSITIONS */
// TODO

#define DOORS_LEFT_OPEN_POS 15
#define DOORS_LEFT_CLOSED_POS 150
#define DOORS_RIGHT_OPEN_POS 150
#define DOORS_RIGHT_CLOSED_POS 15

#define CLAMP_OPEN_POS 48
#define CLAMP_CLOSED_POS 113

#define CLAMPHORIZ_OPEN_POS 40
#define CLAMPHORIZ_CLOSED_POS 6

#define CLAMPELEVATOR_UP_POS 50
#define CLAMPELEVATOR_DOWN_POS 5

/* PINS */
// TODO with elec

#define DOORS_LEFT_PIN 6
#define DOORS_RIGHT_PIN 20

#define CLAMP_PIN 21
#define CLAMPHORIZ_PIN 4

#define CLAMPELEVATOR_PIN 5

#define ULTRASONIC_L_TRIG_PIN 23
#define ULTRASONIC_L_ECHO_PIN 22
#define ULTRASONIC_R_TRIG_PIN 7
#define ULTRASONIC_R_ECHO_PIN 8

#endif

/* OTHER */
#define ULTRASONIC_MEASURE_INTERVAL 50 // ms
#define ULTRASONIC_TRIG_INTERVAL 10    // us
#define ULTRASONIC_SOUND_SPEED 0.034   // us/cm

#define CALLBACK_INTERVAL 1000 // ms
